name = "StaticStrings"
uuid = "a1016230-2428-46eb-b946-443bc93b0a81"
authors = ["Paul Nemec <paul.nemec@tum.de> and contributors"]
version = "0.0.1"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
